##########################################################
######################### ENERGY #########################
##########################################################
- alias: Change utility tariffs to F1
  trigger:
    - platform: time
      at:
        - '08:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
  - service: utility_meter.select_tariff
    data:
      entity_id:
        - utility_meter.daily_energy_consumption_kwh
        - utility_meter.monthly_energy_consumption_kwh
        - utility_meter.yearly_energy_consumption_kwh
      tariff: f1

- alias: Change utility tariffs to F2 on weekdays
  trigger:
    - platform: time
      at: 
        - '07:00:00'
        - '19:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
  - service: utility_meter.select_tariff
    data:
      entity_id:
        - utility_meter.daily_energy_consumption_kwh
        - utility_meter.monthly_energy_consumption_kwh
        - utility_meter.yearly_energy_consumption_kwh
      tariff: f2

- alias: Change utility tariffs to F2 on saturday
  trigger:
    - platform: time
      at: 
        - '07:00:00'
  condition:
    - condition: time
      weekday:
        - sat
  action:
  - service: utility_meter.select_tariff
    data:
      entity_id:
        - utility_meter.daily_energy_consumption_kwh
        - utility_meter.monthly_energy_consumption_kwh
        - utility_meter.yearly_energy_consumption_kwh
      tariff: f2

- alias: Change utility tariffs to F3 on weekdays and saturday
  trigger:
    - platform: time
      at: 
        - '23:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
  action:
  - service: utility_meter.select_tariff
    data:
      entity_id:
        - utility_meter.daily_energy_consumption_kwh
        - utility_meter.monthly_energy_consumption_kwh
        - utility_meter.yearly_energy_consumption_kwh
      tariff: f3

- alias: Change utility tariffs to F3 on sunday
  trigger:
    - platform: time
      at: 
        - '00:00:00'
  condition:
    - condition: time
      weekday:
        - sun
  action:
  - service: utility_meter.select_tariff
    data:
      entity_id:
        - utility_meter.daily_energy_consumption_kwh
        - utility_meter.monthly_energy_consumption_kwh
        - utility_meter.yearly_energy_consumption_kwh
      tariff: f3


##########################################################
########################## EXTRA #########################
##########################################################
- alias: Automatic theme change
  initial_state: 'on' 
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sun.sun
      to: above_horizon
    - platform: state
      entity_id: sun.sun
      to: below_horizon
  condition: []
  action:
    - service_template: frontend.set_theme
      data_template:
        name: >
          {% if states.sun.sun.state == "above_horizon" %}
            Google Light Theme
          {% else %}
            Google Dark Theme
          {% endif %}
    - delay: 00:00:02
    - service: notify.notify
      data_template:
        message: >-
          It is {{ as_timestamp(now()) | timestamp_custom("%X") }},
          sun is {{ states.sun.sun.state | regex_replace(find='_', replace=' ')}}
          and frontend is set.  

- alias: Update notification
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: 'off'
      to: 'on'
  action:
    - service: notify.notify
      data_template:
        message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is now available."

- alias: Garbage collection notification
  trigger:
    - platform: time
      at: 
        - '21:00:00'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.bio_waste
        state: 'tomorrow'
      - condition: state
        entity_id: sensor.packaging_waste_no_glass
        state: 'tomorrow'
      - condition: state
        entity_id: sensor.unsorted_waste
        state: 'tomorrow'
      - condition: state
        entity_id: sensor.paper_waste
        state: 'tomorrow'
  variables:
    waste: >-
      {% if states.sensor.bio_waste.state == 'tomorrow' %} 
        {{ states.sensor.bio_waste.name }} 
      {% elif states.sensor.packaging_waste_no_glass.state == 'tomorrow' %}
        {{ states.sensor.packaging_waste_no_glass.name }}
      {% elif states.sensor.unsorted_waste.state == 'tomorrow' %}
        {{ states.sensor.unsorted_waste.name }}
      {% elif states.sensor.paper_waste.state == 'tomorrow' %}
        {{ states.sensor.paper_waste.name }}
      {% endif %}
  action:
    - service: notify.notify
      data_template:
        message: 'Did you put the "{{ waste | lower }}" garbage outside?'
