##########################################################
######################## GENERIC #########################
##########################################################
config:
history:
map:
mobile_app:
sun:
system_health:
updater:
zeroconf:
python_script:
shopping_list:
wake_on_lan:

homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 98
  temperature_unit: C
  time_zone: Europe/Rome
  unit_system: metric


##########################################################
########################## UI ############################
##########################################################
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/custom-header/custom-header.js
      type: module
    - {type: js, url: '/hacsfiles/garbage-collection-card/garbage-collection-card.js'}
    - url: /hacsfiles/spotify-card/spotify-card.js
      type: module
    - url: /hacsfiles/circle-sensor-card/circle-sensor-card.js
      type: module
    - url: /hacsfiles/battery-state-card/battery-state-card.js
      type: module
  dashboards:
    ui-day-area:
      mode: yaml
      filename: ui-day-area.yaml
      title: Day area
      icon: mdi:sunglasses
      show_in_sidebar: true
      require_admin: false
    ui-night-area:
      mode: yaml
      filename: ui-night-area.yaml
      title: Night area
      icon: mdi:bunk-bed
      show_in_sidebar: true
      require_admin: false
    ui-basement-area:
      mode: yaml
      filename: ui-basement-area.yaml
      title: Basement area
      icon: mdi:home-floor-b
      show_in_sidebar: true
      require_admin: false

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/custom-sidebar/custom-sidebar.js


##########################################################
#################### EXTERNAL FILES ######################
##########################################################
automation: !include automations.yaml
group: !include groups.yaml
person: !include persons.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
zone: !include zones.yaml


##########################################################
##################### MEDIA PLAYERS ######################
##########################################################
alexa_media:
  accounts:
    - email: !secret amazon_email
      password: !secret amazon_password
      url: amazon.it
      include_devices:
        - "Echo Dot di Alessio"

webostv:
  - host: !secret living_room_tv
    name: Living room TV
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret living_room_mac
    customize:
      sources:
        - Sky
        - DVD
        - Soundbar
        - Netflix
        - Amazon Prime Video
        - DAZN
        - Rai Replay
        - YouTube
        - Browser Web

samsungtv:
  - host: !secret basement_living_room_tv_ip
    name: Basement living room TV

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key


##########################################################
################### CUSTOM COMPONENTS ####################
##########################################################
hacs:
  token: !secret hacs_github_token
  appdaemon: true
  netdaemon: true
  experimental: false

climate:
  - platform: climate_group
    name: Thermostats
    temperature_unit: C
    entities:
      - climate.zona_giorno_termostato
      - climate.zona_notte_termostato
      - climate.taverna_termostato

vimar_platform:
  username: !secret vimar_user
  password: !secret vimar_password
  host: !secret vimar_ip
  certificate: 

garbage_collection:
  sensors:
    - name: "Bio waste"
      frequency: "weekly"
      verbose_state: true
      date_format: "%d/%m/%Y"
      verbose_format: "In {days} days"
      collection_days: 
        - "mon"
        - "fri"
    - name: "Packaging waste (no glass)"
      frequency: "weekly"
      verbose_state: true
      date_format: "%d/%m/%Y"
      verbose_format: "In {days} days"
      collection_days: "wed"
    - name: "Unsorted waste"
      frequency: "weekly"
      verbose_state: true
      date_format: "%d/%m/%Y"
      verbose_format: "In {days} days"
      collection_days: "tue"
    - name: "Paper waste"
      frequency: "weekly"
      verbose_state: true
      date_format: "%d/%m/%Y"
      verbose_format: "In {days} days"
      collection_days: "thu"


##########################################################
######################## LOGGERS #########################
##########################################################
logger:
  default: warning
  logs:
    custom_components.vimar_platform: debug


##########################################################
######################### EXTRA ##########################
##########################################################
tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: tts

utility_meter:
  daily_energy_consumption_kwh:
    source: sensor.energy_consumption_kwh
    cycle: daily
  monthly_energy_consumption_kwh:
    source: sensor.energy_consumption_kwh
    cycle: monthly

speedtestdotnet:
  server_id: 2710
  scan_interval:
    minutes: 30

mqtt:
  broker: !secret mqtt_broker_ip
