- platform: template
  sensors:
    energy_consumption_w:
      friendly_name: "Energy consumption"
      unit_of_measurement: W
      value_template: "{{ state_attr('sensor.carichi_globale_controllo_consumo_totale', 'status_value') | float / 1000}}"

- platform: integration
  source: sensor.carichi_globale_controllo_consumo_totale
  name: energy_consumption_kwh
  unit: kW
  unit_time: h
  round: 2
  method: left

# - platform: template
#   sensors:
#     energy_consumption_kwh:
#       entity_id: sensor.energy_consumption_kwh
#       value_template: '0.0'

- platform: template
  sensors:
    mean_temperature:
      friendly_name: "Mean temperature"
      unit_of_measurement: C
      value_template: "{{ state_attr('climate.thermostats', 'current_temperature')}}"
