title: Functions
views:
  - path: thermostats
    title: Thermostats
    icon: mdi:home-thermometer
    cards:
      - type: entities
        entities:
          - climate.thermostats
  - path: media
    title: Media
    icon: mdi:folder-multiple-image
    cards:
      - type: entities
        entities:
          - media_player.falacast_cucina
          - media_player.echo_dot_di_alessio
          - media_player.google_home_salotto
