title: Home
custom_header:  
  button_text:  
    options: '{{ time }}<br>{{ date }}'
views:
  - path: overview
    title: Overview
    icon: mdi:cube-scan
    badges:
      - entity: person.alessio
      - entity: person.lorenzo
      - entity: person.samuele
      - entity: person.cristina
      - entity: sun.sun
    cards:
      - type: vertical-stack
        title: Bulk controls
        cards:
          - type: horizontal-stack
            cards:
              - type: button
                entity: switch.off_tapparelle
                name: All covers down
                icon: mdi:window-shutter
                tap_action:
                  action: toggle
              - type: button
                entity: switch.off_luci
                name: All lights off
                icon: mdi:lightbulb-outline
                tap_action:
                  action: toggle
          - type: custom:auto-entities
            show_empty: false
            card:
              type: glance
              title: Lights on
            filter:
              include:
                - domain: light
                  state: "on"
                  options:
                    tap_action:
                      action: toggle
                  not:
                    name: /[Cc]lima/
          - type: custom:auto-entities
            show_empty: false
            card:
              type: glance
              title: A/Cs on
            filter:
              include:
                - domain: light
                  name: /[Cc]lima On/Off/
                  state: "on"
                  options:
                    tap_action:
                      action: toggle
      - type: vertical-stack
        title: Energy consumption
        cards:
          - type: sensor
            name: Energy consumption
            icon: mdi:power-plug
            entity: sensor.carichi_globale_controllo_consumo_totale
            graph: line
            unit: kW
            detail: 1
          - type: sensor
            name: Daily energy spent
            icon: mdi:power-plug
            entity: sensor.daily_energy_consumption_kwh
            unit: kWh
          - type: sensor
            name: Monthly energy spent
            icon: mdi:power-plug
            entity: sensor.monthly_energy_consumption_kwh
            unit: kWh
          - type: sensor
            name: Yearly energy spent
            icon: mdi:power-plug
            entity: sensor.yearly_energy_consumption_kwh
            unit: kWh
      - type: vertical-stack
        title: Energy cost
        cards:
          - type: sensor
            name: Daily energy cost
            icon: mdi:currency-eur
            entity: sensor.daily_energy_cost
            unit: "€"
          - type: sensor
            name: Monthly energy cost
            icon: mdi:currency-eur
            entity: sensor.monthly_energy_cost
            unit: "€"
          - type: sensor
            name: Yearly energy cost
            icon: mdi:currency-eur
            entity: sensor.yearly_energy_cost
            unit: "€"
      - type: vertical-stack
        title: Temperature
        cards:
          - type: thermostat
            entity: climate.thermostats
          - type: sensor
            name: Mean temperature
            icon: mdi:home-thermometer
            entity: sensor.mean_temperature
            graph: line
            unit: "°C"
            detail: 1
          - type: weather-forecast
            entity: weather.home
      - type: vertical-stack
        title: Garbage collection
        cards:
          - type: custom:garbage-collection-card
            entity: sensor.bio_waste
            icon_color: brown
          - type: custom:garbage-collection-card
            entity: sensor.packaging_waste_no_glass
            icon_color: blue
          - type: custom:garbage-collection-card
            entity: sensor.unsorted_waste
            icon_color: grey
          - type: custom:garbage-collection-card
            entity: sensor.paper_waste
            icon_color: yellow
  - path: server
    title: Server
    icon: mdi:server
    cards:
      - type: vertical-stack
        title: Speedtest statistics
        cards:
          - type: sensor
            name: Download rate
            icon: mdi:download
            entity: sensor.speedtest_download
            graph: line
            unit: Mbit/s
            detail: 1
          - type: sensor
            name: Upload rate
            icon: mdi:upload
            entity: sensor.speedtest_upload
            graph: line
            unit: Mbit/s
            detail: 1
          - type: sensor
            name: Ping rate
            icon: mdi:weather-cloudy-arrow-right
            entity: sensor.speedtest_ping
            graph: line
            unit: ms
            detail: 1
      - type: vertical-stack
        title: System monitoring
        cards:
          - type: gauge
            name: CPU temperature
            entity: sensor.cpu_temperature
            unit: "°C"
            min: 0
            max: 100
            severity:
              green: 0
              yellow: 45
              red: 85
          - type: gauge
            name: CPU usage
            entity: sensor.cpu_usage
            unit: "%"
            min: 0
            max: 100
            severity:
              green: 0
              yellow: 65
              red: 90
          - type: gauge
            name: RAM usage
            entity: sensor.ram_usage
            unit: "%"
            min: 0
            max: 100
            severity:
              green: 0
              yellow: 65
              red: 90
          - type: gauge
            name: Storage usage
            entity: sensor.storage_usage
            unit: "%"
            min: 0
            max: 100
            severity:
              green: 0
              yellow: 50
              red: 80
      - type: custom:battery-state-card
        title: "Phones battery levels"
        sort_by_level: "desc"
        thresholds:
          - value: 10
            color: "#c0392b"
          - value: 20
            color: "#f39c12"
          - value: 40
            color: "#f1c40f"
          - value: 60
            color: "#2ecc71"
        charging_state:
          attribute:
            name: "Battery State"
            value: "Charging"
        entities:
          - entity: sensor.iphone_x_di_jobs_battery_level
            name: "Alessio's iPhone X"
  - path: printers
    title: Printers
    icon: mdi:printer
    cards:
      - type: vertical-stack
        title: Xerox printer status
        cards:
          - type: entity
            entity: sensor.xerox_printer_page_count
            icon: mdi:book-open-page-variant
          - type: horizontal-stack
            title: Toner levels
            cards:
              - type: custom:circle-sensor-card
                entity: sensor.xerox_printer_cyan_toner_level
                show_card: false
                fill: "#ecf0f1"
                stroke_width: 10
                stroke_color: cyan
                units: '%'
                show_max: false
                font_style:
                  font-size: 1.5em
                  color: black
              - type: custom:circle-sensor-card
                entity: sensor.xerox_printer_magenta_toner_level
                show_card: false
                fill: "#ecf0f1"
                stroke_width: 10
                stroke_color: magenta
                units: '%'
                show_max: false
                font_style:
                  font-size: 1.5em
                  color: black
              - type: custom:circle-sensor-card
                entity: sensor.xerox_printer_yellow_toner_level
                show_card: false
                fill: "#ecf0f1"
                stroke_width: 10
                stroke_color: yellow
                units: '%'
                show_max: false
                font_style:
                  font-size: 1.5em
                  color: black
              - type: custom:circle-sensor-card
                entity: sensor.xerox_printer_black_toner_level
                show_card: false
                fill: "#ecf0f1"
                stroke_width: 10
                stroke_color: black
                units: '%'
                show_max: false
                font_style:
                  font-size: 1.5em
                  color: black
      - type: vertical-stack
        title: Samsung printer status
        cards:
          - type: entity
            entity: sensor.samsung_printer_page_count
            icon: mdi:book-open-page-variant
          - type: horizontal-stack
            title: Toner levels
            cards:
              - type: custom:circle-sensor-card
                entity: sensor.zero_sensor
                show_card: false
                fill: "#c0392b"
                stroke_width: 10
                stroke_color: cyan
                units: '%'
                show_max: false
                font_style:
                  font-size: 1.5em
                  color: black
              - type: custom:circle-sensor-card
                entity: sensor.zero_sensor
                show_card: false
                fill: "#c0392b"
                stroke_width: 10
                stroke_color: magenta
                units: '%'
                show_max: false
                font_style:
                  font-size: 1.5em
                  color: black
              - type: custom:circle-sensor-card
                entity: sensor.zero_sensor
                show_card: false
                fill: "#c0392b"
                stroke_width: 10
                stroke_color: yellow
                units: '%'
                show_max: false
                font_style:
                  font-size: 1.5em
                  color: black
              - type: custom:circle-sensor-card
                entity: sensor.samsung_printer_black_toner_level
                show_card: false
                fill: "#ecf0f1"
                stroke_width: 10
                stroke_color: black
                units: '%'
                show_max: false
                font_style:
                  font-size: 1.5em
                  color: black
  - path: media
    title: Media players
    icon: mdi:popcorn
    cards:
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
          title: Media players
        filter:
          include:
            - domain: media_player
          exclude:
            - name: /[Ss]potify/
            - name: /[Pp]lex/
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
          title: Plex sources
        filter:
          include:
            - entity_id: /media_player.plex/
      - type: "custom:spotify-card"
        name: Playlists
        account: "default"
        country_code: IT
        limit: 9
        # display_style: Grid
        grid_covers_per_row: 3
